### ISSUE TITLE
好像还是不支持kotlin项目

### ISSUE THREAD

**Issue by wva37254626** [ParfoisMeng/Android-ButterKnife-Injections#1]
还是操作不对还是什么,我的kotlin项目无法用
已经加载了插件也引入了butterknife库
但是还在引用布局R.layout.activity_main位置调用不出来
是跟studio版本有关还是有其他的操作
我的android studio3.3.2 ,gradle-4.10.1,kotlin_version = '1.3.30'

**Comment by ParfoisMeng** [comment]
如果你是在.kt文件中使用，那是肯定用不了的。
插件说明有写明：“适用于父类为kt文件，子类为java文件的情况。”
如果符合情况还不能用，麻烦贴一下报错看看？
