### ISSUE TITLE
Android 4.1 修复方案

### ISSUE THREAD

**Issue by narakai** [ParfoisMeng/Android-ButterKnife-Injections#10]
此方案为mac上的，windows应该同理

使插件可用：
1. 下载jar包
2. 找到应用程序-Android Studio，右键-显示包内容，找到Contents-plugins，新建一个文件夹，命名可随意，在新文件夹下建立lib文件夹，把jar拷贝进去，重启就可以用了

清除开机插件报错：
删除~/Library/Application Support/Google/AndroidStudio4.1/plugins下报错的插件即可

**Comment by ParfoisMeng** [comment]
嗯嗯。我这就更新README
