### ISSUE TITLE
老哥，最新版的AS4.1.1咋办啊，求更新兼容4.1.1

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [ParfoisMeng/Android-ButterKnife-Injections#11]
如题，感谢老哥了，这个插件真的很好用😃

**Comment by ParfoisMeng** [comment]
README已更新兼容使用方法。

**Comment by SaltedFish-Extreme** [comment]
> README已更新兼容使用方法。

不行啊，我试过好几次了，放在AS的插件根目录下，在最新的4.1.1版本里还是会报错不兼容不显示插件也没法使用快捷生成butterknife😥

**Comment by ParfoisMeng** [comment]
我这里可以啊……
你看看这个[issues10](https://github.com/ParfoisMeng/Android-ButterKnife-Injections/issues/10)

**Comment by SaltedFish-Extreme** [comment]
> 我这里可以啊……
> 你看看这个[issues10](https://github.com/ParfoisMeng/Android-ButterKnife-Injections/issues/10)

好了，可以使用并且不报错了，感谢老哥和提出那个解决办法的人了😄
