### ISSUE TITLE
AS4.1

### ISSUE THREAD

**Issue by 211885646** [ParfoisMeng/Android-ButterKnife-Injections#12]
AS4.1根据描述吧jar包粘贴到了对应的目录 但是重启AS后依然会丢失  但是目录中是有jar文件的

**Comment by ParfoisMeng** [comment]
> 删除 ~/Library/Application Support/Google/AndroidStudio4.1/plugins 下报错的插件

试试

**Comment by 211885646** [comment]
刚试完~~~删除了 整个pligins目录   启动as会自动生成
jar复制进去 ,再重启as  还是没得

**Comment by 211885646** [comment]
而且我发现 能用的插件在此目录是解压出来了的 不是jar形式存在的  比如我现在用的GsonFormatPlus

**Comment by ParfoisMeng** [comment]
听起来好像搞错了？

> - MAC：下载jar包，粘贴至 "~/Applications/Android Studio.app/Contents/plugins" 路径下，重启 AS 即可。
> - Windows：下载jar包，粘贴至 "C:\Users\username\AppData\Roaming\Google\AndroidStudio4.1\plugins" 路径下，重启 AS 即可。
> > 清除报错：删除 ~/Library/Application Support/Google/AndroidStudio4.1/plugins 下报错的插件。

两个不同的地方。AS4.1好像是旧的用户插件无法使用了，所以将其移至系统插件目录下使用。

**Comment by ParfoisMeng** [comment]
如果始终不行的话，我也不知道为什么了。
一定要用的话也可以考虑AS降级，不过……建议转 kotlin 吧。

**Comment by zsj8580** [comment]
将插件jar放到Studio的安装目录下的 C:\Program Files\Android\Android Studio\plugins\Android-ButterKnife-Injections\lib 下（这是我的studio安装目录，非C:\Users\username\AppData\Roaming\Google\下的AS目录），重启亲测可用

**Comment by 211885646** [comment]
不行  我的AS是解压版  我看了安装目录plugins下没有Android-ButterKnife-Injections这个

**Comment by 211885646** [comment]
大佬牛皮 原来是要手动新建这个目录啊 现在可以了
