### ISSUE TITLE
最新Android Studio Arctic Fox (2020.3.1)  使用不了

### ISSUE THREAD

**Issue by xiechunjiang** [ParfoisMeng/Android-ButterKnife-Injections#13]
此版本，使用不了
![1627611755(1)](https://user-images.githubusercontent.com/12966578/127590644-0dfc71b8-042c-47c1-934d-8c76820bdc49.jpg)

**Comment by amigo-wangwx** [comment]
没错,今天升级之后各种办法都试了,都不行

**Comment by ParfoisMeng** [comment]
我修不了啦，这个项目在新的IDE里面咋都打不开……你们也可以clone源码看看改改然后PR呀！
@xiechunjiang @GitHubWebb

**Comment by SaltedFish-Extreme** [comment]
难受，2020.3.1版本有挺多问题的，主题没有高亮了，有个暗黑主题插件也不显示，必须把as自带插件的gosn改后缀名才行，但是这个插件还是不能用，不知道这两者之间会不会有什么关系，还有代码也不分析语法错误也不会自动导包了啥的，中文汉化包要找合适的版本导入才行，想退到之前版本官网又找不到旧版本，只能等更新了

**Comment by fiytodie** [comment]
我也是...头大，请问有没有什么其它替代的呢？

**Comment by RedDargon** [comment]
同问 有解决方法吗

**Comment by xiechunjiang** [comment]
@GitHubWebb @RedDargon @ParfoisMeng @fiytodie  今天找到一个插件可以用此版本（Android Studio Artic Fox | 2020.3.1 Patch 3
）能正常使用，不过kotlin 的好像不行，java项目可以，kotlin其实也不需要  直接Plugins 中搜索IDsCreate [  https://plugins.jetbrains.com/plugin/9505-idscreate](url)

**Comment by ParfoisMeng** [comment]
@xiechunjiang 
建议改用View Binding。

JakeWharton 官宣 ButterKnife 停止维护都一年半之久了。
> Butter Knife
> Attention: This tool is now deprecated. Please switch to view binding. Existing versions will continue to work, obviously, but only critical bug fixes for integration with AGP will be considered. Feature development and general bug fixes have stopped.

**Comment by xiechunjiang** [comment]
嗯，这只是维护以前的老项目中有，不想动



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月14日(星期四) 下午2:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ParfoisMeng/Android-ButterKnife-Injections] 最新Android Studio Arctic Fox (2020.3.1)  使用不了 (#13)





 
@xiechunjiang
 建议改用View Binding。
 
JakeWharton 官宣 ButterKnife 停止维护都一年半之久了。
  
Butter Knife
 Attention: This tool is now deprecated. Please switch to view binding. Existing versions will continue to work, obviously, but only critical bug fixes for integration with AGP will be considered. Feature development and general bug fixes have stopped.

**Comment by SaltedFish-Extreme** [comment]
> @GitHubWebb @RedDargon @ParfoisMeng @fiytodie 今天找到一个插件可以用此版本（Android Studio Artic Fox | 2020.3.1 Patch 3 ）能正常使用，不过kotlin 的好像不行，java项目可以，kotlin其实也不需要 直接Plugins 中搜索IDsCreate [ https://plugins.jetbrains.com/plugin/9505-idscreate](url)

啊，刚才看了下你发的这个插件，在kotlin中好像没法用啊，我一直用的android findviewbyid support，但是在kotlin中生成的id没法直接插入代码，目前在用find view for Android，用着还行，还有插件市场有butter knife一键转findviewbyid的插件，可以试试

**Comment by SaltedFish-Extreme** [comment]
到头来还是回归初心使用findviewbyid才是王道🤣
