### ISSUE TITLE
请问插件没了吗？下载jar包地址链接被重置了，是把发布版取消了吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [ParfoisMeng/Android-ButterKnife-Injections#14]
如题

**Comment by ParfoisMeng** [comment]
![image](https://user-images.githubusercontent.com/14328312/130171476-c992650c-a7f9-40c2-a4fb-9b68adf1c5d5.png)

**Comment by ParfoisMeng** [comment]
但是据其他网友反馈，新版AS无法使用了。

**Comment by SaltedFish-Extreme** [comment]
> 据其他网友反馈，新版AS无法使用了。

是这样，所以最后我退回到4.2.2版本了😂经常需要用到这个插件，能提供下最新版的下载地址吗😉
![image](https://user-images.githubusercontent.com/54784104/130171736-644c4b17-697f-4009-8356-14e34fefdb03.png)

**Comment by SaltedFish-Extreme** [comment]
啊，刚才没加载出来图片，没看到项目里带的jar包，不好意思了😂
