### ISSUE TITLE
【建议】生成的字段是m开头，符合android code style?

### ISSUE THREAD

**Issue by tainzhi** [ParfoisMeng/Android-ButterKnife-Injections#3]
比如生成的mTextView，以m开头，符合android code style.

**Comment by ParfoisMeng** [comment]
生成字段的规则与 [Android ButterKnife Zelezny](https://github.com/avast/android-butterknife-zelezny) 一致。其规则大概：取出xml中控件ID，将下划线命名改为小驼峰命名，所以如果你很想要“m”开头那种，也许可以试试在xml中设置id加上“m”。

PS: 可能每个人的习惯不一样，我并不喜欢这种“m”开头的方式。

**Comment by tainzhi** [comment]
可以加个开关吗？ps.是不是需求太多了^_^

**Comment by ParfoisMeng** [comment]
这个需求。。说实话不太想做，建议你Clone下来自行修改。关键代码见[此处](https://github.com/ParfoisMeng/Android-ButterKnife-Injections/blob/e6d564874c1cbfcdddeaa321a09b90ea9d1b95b8/src/com/avast/android/butterknifezelezny/model/Element.java#L116)。

**Comment by tainzhi** [comment]
恩恩。谢谢非常耐心的指导。

**Comment by ParfoisMeng** [comment]
@tainzhi 今天在看别的问题时发现原Android ButterKnife Zelezny是有这个功能的，我测试了一下的确有效。你可以试一下看是否满足你的需求。
![image](https://user-images.githubusercontent.com/14328312/64936922-d446b180-d88a-11e9-8dc7-b0f02e6d0720.png)

**Comment by tainzhi** [comment]
我看了下，的确可以，完全满足我的需求。太好了。非常非常感谢

**Comment by mcxinyu** [comment]
这个 m 是 member（成员变量） 的意思啊，类似 static（静态变量） 就是 s 开头，java code 约定俗成的不就是这样么？你可以试下用 idea 重命名变量，会给你对应的提示，上面就沿用了这种规则。
![image](https://user-images.githubusercontent.com/9566116/98904877-63824000-24f5-11eb-86b6-61e8e14fea65.png)
