### ISSUE TITLE
AS 3.4.1 插件加载失败

### ISSUE THREAD

**Issue by Del-Gin** [ParfoisMeng/Android-ButterKnife-Injections#4]
我在AS中搜索并下载此插件，重启AS之后，在已安装的插件列表中找不到此插件，重启时发现，AS自动将此插件从plugins目录下删除了

**Comment by ParfoisMeng** [comment]
没有遇到过这种问题。你试试下载jar包导入安装？
另外，此插件和“Android ButterKnife Zelezny”一致，快捷键也是一样的，所以可能有冲突，建议卸载“Android ButterKnife Zelezny”。
