### ISSUE TITLE
和项目无关的问题

### ISSUE THREAD

**Issue by hyhyhykw** [ParfoisMeng/Android-ButterKnife-Injections#7]
为什么用了kotlin还要用butterknife呢，kotlin-android-extensions不是更好用，而且资源还能混淆，用了butterknife都不能混淆资源了

**Comment by ParfoisMeng** [comment]
1，对于一些老旧项目，你可以相对容易的将它们的BaseActivity抽出来用Kotlin重写并优化，但是，继承于BaseActivity的其他的Activity还有很多，而你很难将它们都转成Kotlin。所以，虽然kotlin-android-extensions更好用，但butterknife还是扔不掉。
2，哪怕Kotlin再怎么易学，不可否认它依然有学习成本，你会不代表你团队里所有人都会。这是个过程。
![image](https://user-images.githubusercontent.com/14328312/66381659-52aaf500-e9ec-11e9-848c-d4b613700ac8.png)
