### ISSUE TITLE
Plugin Error: Plugin "Android ButterKnife Injections (Support Kotlin)" is incompatible (supported only in IntelliJ IDEA).

### ISSUE THREAD

**Issue by KuiYang2017** [ParfoisMeng/Android-ButterKnife-Injections#8]
升级新版studio(4.1)以后 出现此问题

**Comment by ParfoisMeng** [comment]
AS 4.1 兼容问题，因为原库早已不更新，目前暂无修复方案

**Comment by KuiYang2017** [comment]
将插件从用户插件存放位置挪到studio自带插件位置 可以正常使用

**Comment by ParfoisMeng** [comment]
> 将插件从用户插件存放位置挪到studio自带插件位置 可以正常使用

嗯？可以说明一下操作流程吗？我整理一下发到README中。

**Comment by KuiYang2017** [comment]
4.1 插件安装的地址 在 **C:\Users\Administrator\AppData\Roaming\Google\AndroidStudio4.1\plugins** 这个地方，从这里找到不兼容的插件，将插件放到Studio的安装目录下的   **xx\Android Studio\plugins** 下 即可

**Comment by helinyun98** [comment]
直接下载jar放入Studio的自带插件目录就可以使用了，插件管理里显示为bundled
Mac OS 的目录是 /Applications/Android\ Studio.app/Contents/plugins/

**Comment by dahaiChang** [comment]
> 4.1 插件安装的地址 在 **C:\Users\Administrator\AppData\Roaming\Google\AndroidStudio4.1\plugins** 这个地方，从这里找到不兼容的插件，将插件放到Studio的安装目录下的 **xx\Android Studio\plugins** 下 即可

Android Studio 2020.03版本不适用
