### ISSUE TITLE
AndroidStudio4.1升级后显示插件不兼容

### ISSUE THREAD

**Issue by tianxiake** [ParfoisMeng/Android-ButterKnife-Injections#9]
大佬,Android Studio4.1显示Incompatible(supported only int intellij IDEA)

**Comment by ParfoisMeng** [comment]
[issues_8](https://github.com/ParfoisMeng/Android-ButterKnife-Injections/issues/8)：

> AS 4.1 兼容问题，因为原库早已不更新，目前暂无修复方案
